import { useColorScheme } from "@/hooks/use-color-scheme";
import { useAuth } from "@/hooks/useAuth";
import { useScrollToTop } from "@react-navigation/native";
import { router } from "expo-router";
import { BlurView } from "expo-blur";
import * as Clipboard from "expo-clipboard";
import { useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

import { addTask, deleteAllTasks, deleteCompletedTasks, getTasks } from "@/lib/database";

export default function SettingsScreen() {
  const scheme = useColorScheme();
  const dark = scheme === "dark";
  const { user, signOut } = useAuth();
  const scrollRef = useRef<ScrollView>(null);
  useScrollToTop(scrollRef);

  // States
  const [notifications, setNotifications] = useState(true);
  const [appLock, setAppLock] = useState(false);
  const [signingOut, setSigningOut] = useState(false);

  // Colors
  const background = dark ? "#1C1C1E" : "#f2f2f7";
  const card = dark ? "#2C2C2E" : "#fff";
  const text = dark ? "#ffffff" : "#000";
  const subtext = dark ? "#D1D1D6" : "#555";

  /* DOUBLE CONFIRM DELETE FUNCTION */
  const clearAllData = () => {
    Alert.alert(
      "Are you sure?",
      "This will delete all tasks.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Continue",
          style: "destructive",
          onPress: () => {
            // SECOND CONFIRMATION
            Alert.alert(
              "Really delete all tasks?",
              "This action cannot be undone.",
              [
                { text: "Cancel", style: "cancel" },
                {
                  text: "Delete",
                  style: "destructive",
                  onPress: async () => {
                    try {
                      await deleteAllTasks();
                      console.log("All tasks deleted.");
                    } catch (error) {
                      console.error("Failed to delete tasks", error);
                      Alert.alert("Delete failed", "Please try again after signing in.");
                    }
                  },
                },
              ],
              { userInterfaceStyle: dark ? "dark" : "light" }
            );
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  const handleSignOut = () => {
    Alert.alert(
      "Sign out?",
      "You'll need to log back in to see your tasks.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Sign out",
          style: "destructive",
          onPress: async () => {
            try {
              setSigningOut(true);
              await signOut();
              router.replace("/login");
            } finally {
              setSigningOut(false);
            }
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  // Quick seed with dummy data for demos
  const seedDummyTasks = async () => {
    const difficulties = ["easy", "medium", "hard"] as const;
    const subjects = ["Math", "Science", "History", "English", "CS", "Art"];
    const verbs = ["Review", "Draft", "Complete", "Revise", "Outline", "Sketch"];
    const nouns = ["essay", "lab", "notes", "project", "quiz prep", "slides"];

    const today = new Date();
    const pad = (n: number) => String(n).padStart(2, "0");
    const formatDate = (offset: number) => {
      const d = new Date(today);
      d.setDate(today.getDate() + offset);
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
    };

    try {
      const payload = Array.from({ length: 10 }).map(() => {
        const title = `${verbs[Math.floor(Math.random() * verbs.length)]} ${
          nouns[Math.floor(Math.random() * nouns.length)]
        } (${subjects[Math.floor(Math.random() * subjects.length)]})`;
        const difficulty = difficulties[Math.floor(Math.random() * difficulties.length)];
        const dateOffset = Math.floor(Math.random() * 14) - 2; // a mix of overdue + near-term
        const due_date = formatDate(dateOffset);

        return {
          title,
          description: `${title} - autogenerated demo task`,
          difficulty,
          due_date,
        };
      });

      await Promise.all(payload.map((task) => addTask(task)));
      Alert.alert("Dummy tasks added", "10 random tasks were created for you.");
    } catch (err) {
      console.error("Failed to seed dummy tasks", err);
      Alert.alert("Couldn't add dummy tasks", "Please try again.");
    }
  };

  const exportTasks = async () => {
    try {
      const tasks = await getTasks();
      const payload = JSON.stringify(tasks, null, 2);
      await Clipboard.setStringAsync(payload);
      Alert.alert("Exported", "All tasks copied to clipboard as JSON.");
    } catch (err) {
      console.error("Failed to export tasks", err);
      Alert.alert("Export failed", "Couldn't copy tasks to clipboard.");
    }
  };

  const importTasks = async () => {
    try {
      const raw = await Clipboard.getStringAsync();
      if (!raw) {
        Alert.alert("Nothing to import", "Clipboard is empty.");
        return;
      }
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed)) {
        Alert.alert("Invalid format", "Clipboard must contain a JSON array of tasks.");
        return;
      }

      let imported = 0;
      for (const item of parsed) {
        if (!item?.title || !item?.notes || !item?.difficulty) continue;
        const diff = item.difficulty as "easy" | "medium" | "hard";
        if (!["easy", "medium", "hard"].includes(diff)) continue;

        await addTask({
          title: String(item.title),
          description: String(item.notes),
          difficulty: diff,
          due_date: item.due_date ?? null,
        });
        imported += 1;
      }

      Alert.alert("Import complete", `Added ${imported} tasks from clipboard.`);
    } catch (err) {
      console.error("Import failed", err);
      Alert.alert("Import failed", "Couldn't read tasks from clipboard.");
    }
  };

  const clearCompleted = async () => {
    Alert.alert(
      "Clear completed?",
      "This will remove all tasks marked as done.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Remove",
          style: "destructive",
          onPress: async () => {
            try {
              await deleteCompletedTasks();
              Alert.alert("Done", "Completed tasks were removed.");
            } catch (error) {
              console.error("Failed to clear completed tasks", error);
              Alert.alert("Couldn't clear tasks", "Please sign in again and retry.");
            }
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  const resetDemoData = async () => {
    Alert.alert(
      "Reset demo data?",
      "This will delete all tasks and add fresh dummy tasks.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Reset",
          style: "destructive",
          onPress: async () => {
            try {
              await deleteAllTasks();
              await seedDummyTasks();
              Alert.alert("Reset complete", "Dummy tasks have been reloaded.");
            } catch (error) {
              console.error("Failed to reset demo data", error);
              Alert.alert("Reset failed", "Please sign in again and retry.");
            }
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  return (
    <View style={{ flex: 1, backgroundColor: background }}>

      {/* 🔵 TOP BLUR EFFECT */}
      <BlurView
        intensity={40}
        tint={dark ? "dark" : "light"}
        style={styles.blurHeader}
      />

      {/* Smooth fade under blur */}
      <View style={styles.blurFade} />

      <ScrollView
        ref={scrollRef}
        style={styles.container}
        contentContainerStyle={{ paddingBottom: 70, paddingTop: 26 }}
      >

        {/* TITLE */}
        <Text style={[styles.title, { color: text }]}></Text>

        {/* ACCOUNT */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <Text style={[styles.sectionLabel, { color: subtext }]}>Account</Text>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Name</Text>
            <Text style={[styles.value, { color: subtext }]}>
              {user?.name || "Not set"}
            </Text>
          </View>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Email</Text>
            <Text style={[styles.value, { color: subtext }]}>
              {user?.email || "—"}
            </Text>
          </View>

          <TouchableOpacity style={styles.row} onPress={handleSignOut} disabled={signingOut}>
            <Text style={[styles.label, { color: "#FF3B30" }]}>
              {signingOut ? "Signing out..." : "Sign Out"}
            </Text>
            {signingOut && <ActivityIndicator color="#FF3B30" />}
          </TouchableOpacity>
        </View>

        {/* NOTIFICATIONS */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <Text style={[styles.sectionLabel, { color: subtext }]}>
            Notifications
          </Text>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Enable Alerts</Text>
            <Switch
              value={notifications}
              onValueChange={() => setNotifications(!notifications)}
            />
          </View>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Daily Reminder Time</Text>
            <Text style={[styles.value, { color: subtext }]}>09:00</Text>
          </TouchableOpacity>
        </View>

        {/* SECURITY */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <Text style={[styles.sectionLabel, { color: subtext }]}>Security</Text>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>App Lock</Text>
            <Switch value={appLock} onValueChange={() => setAppLock(!appLock)} />
          </View>
        </View>

        {/* DATA */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <Text style={[styles.sectionLabel, { color: subtext }]}>Data</Text>

          <TouchableOpacity style={styles.row} onPress={exportTasks}>
            <Text style={[styles.label, { color: text }]}>Export tasks (clipboard JSON)</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={importTasks}>
            <Text style={[styles.label, { color: text }]}>Import tasks from clipboard</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={seedDummyTasks}>
            <Text style={[styles.label, { color: text }]}>Add 10 dummy tasks</Text>
            <Text style={[styles.value, { color: subtext }]}>Instant</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={clearCompleted}>
            <Text style={[styles.label, { color: text }]}>Clear completed tasks</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={resetDemoData}>
            <Text style={[styles.label, { color: text }]}>Reset demo data</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={clearAllData}>
            <Text style={[styles.label, { color: "#FF3B30" }]}>
              Clear All Tasks
            </Text>
          </TouchableOpacity>
        </View>

        {/* ABOUT */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <Text style={[styles.sectionLabel, { color: subtext }]}>About</Text>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Version</Text>
            <Text style={[styles.value, { color: subtext }]}>1.0.0</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Developer</Text>
            <Text style={[styles.value, { color: subtext }]}>You</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Privacy Policy</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Terms of Service</Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },

  title: {
    fontSize: 32,
    fontWeight: "700",
    marginHorizontal: 16,
    marginBottom: 20,
  },

  card: {
    borderRadius: 16,
    marginBottom: 24,
    paddingVertical: 8,
    marginHorizontal: 16,
    overflow: "hidden",
  },

  sectionLabel: {
    fontSize: 13,
    opacity: 0.7,
    marginBottom: 6,
    marginLeft: 16,
  },

  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 18,
  },

  label: { fontSize: 16 },
  value: { fontSize: 14, opacity: 0.8 },

  /* Blur header */
  blurHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 80,
    zIndex: 20,
  },

  /* Smooth fade under blur */
  blurFade: {
    position: "absolute",
    top: 80,
    left: 0,
    right: 0,
    height: 40,
    zIndex: 19,
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { height: 8, width: 0 },
    shadowRadius: 12,
  },
});
