import { useColorScheme } from "@/hooks/use-color-scheme";
import { useAuth } from "@/hooks/useAuth";
import { useThemeColors } from "../../../hooks/use-theme-colors";
import {
  loadAccessibilityPrefs,
  setFontScale,
  setHapticsEnabled,
  setColorBlindMode,
} from "@/utils/accessibilityPrefs";
import { useFocusEffect, useScrollToTop } from "@react-navigation/native";
import { router } from "expo-router";
import { BlurView } from "expo-blur";
import * as Clipboard from "expo-clipboard";
import DateTimePicker, { DateTimePickerEvent } from "@react-native-community/datetimepicker";
import { useCallback, useMemo, useRef, useState } from "react";
import {
  Alert,
  Modal,
  Platform,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";

import { addTask, deleteAllTasks, deleteCompletedTasks, getTasks } from "@/lib/database";
import { getAppLockState } from "@/lib/app-lock-storage";
import {
  DEFAULT_REMINDER_TIME,
  disableReminder,
  enableReminder,
  formatReminderTime,
  loadReminderSettings,
  saveReminderSettings,
  triggerTestNotification,
} from "@/lib/notifications";

export default function SettingsScreen() {
  const scheme = useColorScheme();
  const dark = scheme === "dark";
  const colors = useThemeColors();
  const { user } = useAuth();
  const scrollRef = useRef<ScrollView>(null);
  useScrollToTop(scrollRef);

  // States
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);
  const [reminderTime, setReminderTime] = useState<{ hour: number; minute: number }>(DEFAULT_REMINDER_TIME);
  const [loadingReminders, setLoadingReminders] = useState(false);
  const [sendingTest, setSendingTest] = useState(false);
  const [appLock, setAppLock] = useState(false);
  const [loadingLock, setLoadingLock] = useState(true);
  const [showTimePicker, setShowTimePicker] = useState(false);
  const [tempTime, setTempTime] = useState<{ hour: number; minute: number }>(DEFAULT_REMINDER_TIME);
  const [fontScale, setFontScaleState] = useState(1);
  const [hapticsEnabled, setHapticsEnabledState] = useState(true);
  const [colorBlindMode, setColorBlindModeState] = useState(false);
  const [loadingAccess, setLoadingAccess] = useState(true);

  // Colors
  const background = colors.background;
  const card = colors.surface;
  const text = colors.textPrimary;
  const subtext = colors.textMuted;

  /* DOUBLE CONFIRM DELETE FUNCTION */
  const clearAllData = () => {
    Alert.alert(
      "Are you sure?",
      "This will delete all tasks.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Continue",
          style: "destructive",
          onPress: () => {
            // SECOND CONFIRMATION
            Alert.alert(
              "Really delete all tasks?",
              "This action cannot be undone.",
              [
                { text: "Cancel", style: "cancel" },
                {
                  text: "Delete",
                  style: "destructive",
                  onPress: async () => {
                    try {
                      await deleteAllTasks();
                      console.log("All tasks deleted.");
                    } catch (error) {
                      console.error("Failed to delete tasks", error);
                      Alert.alert("Delete failed", "Please try again after signing in.");
                    }
                  },
                },
              ],
              { userInterfaceStyle: dark ? "dark" : "light" }
            );
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  // Quick seed with dummy data for demos
  const seedDummyTasks = async () => {
    const difficulties = ["easy", "medium", "hard"] as const;
    const subjects = ["Math", "Science", "History", "English", "CS", "Art"];
    const verbs = ["Review", "Draft", "Complete", "Revise", "Outline", "Sketch"];
    const nouns = ["essay", "lab", "notes", "project", "quiz prep", "slides"];

    const today = new Date();
    const pad = (n: number) => String(n).padStart(2, "0");
    const formatDate = (offset: number) => {
      const d = new Date(today);
      d.setDate(today.getDate() + offset);
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
    };

    try {
      const payload = Array.from({ length: 10 }).map(() => {
        const title = `${verbs[Math.floor(Math.random() * verbs.length)]} ${
          nouns[Math.floor(Math.random() * nouns.length)]
        } (${subjects[Math.floor(Math.random() * subjects.length)]})`;
        const difficulty = difficulties[Math.floor(Math.random() * difficulties.length)];
        const dateOffset = Math.floor(Math.random() * 14) - 2; // a mix of overdue + near-term
        const due_date = formatDate(dateOffset);

        return {
          title,
          description: `${title} - autogenerated demo task`,
          difficulty,
          due_date,
        };
      });

      await Promise.all(payload.map((task) => addTask(task)));
      Alert.alert("Dummy tasks added", "10 random tasks were created for you.");
    } catch (err) {
      console.error("Failed to seed dummy tasks", err);
      Alert.alert("Couldn't add dummy tasks", "Please try again.");
    }
  };

  const refreshLockState = useCallback(async () => {
    const state = await getAppLockState();
    setAppLock(state.enabled);
    setLoadingLock(false);
  }, []);

  const refreshNotifications = useCallback(async () => {
    setLoadingReminders(true);
    try {
      const settings = await loadReminderSettings();
      setNotificationsEnabled(settings.enabled);
      setReminderTime({ hour: settings.hour, minute: settings.minute });
    } finally {
      setLoadingReminders(false);
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      refreshLockState();
      refreshNotifications();
      refreshAccessPrefs();
    }, [refreshLockState, refreshNotifications, refreshAccessPrefs])
  );

  const exportTasks = async () => {
    try {
      const tasks = await getTasks();
      const payload = JSON.stringify(tasks, null, 2);
      await Clipboard.setStringAsync(payload);
      Alert.alert("Exported", "All tasks copied to clipboard as JSON.");
    } catch (err) {
      console.error("Failed to export tasks", err);
      Alert.alert("Export failed", "Couldn't copy tasks to clipboard.");
    }
  };

  const importTasks = async () => {
    try {
      const raw = await Clipboard.getStringAsync();
      if (!raw) {
        Alert.alert("Nothing to import", "Clipboard is empty.");
        return;
      }
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed)) {
        Alert.alert("Invalid format", "Clipboard must contain a JSON array of tasks.");
        return;
      }

      let imported = 0;
      for (const item of parsed) {
        if (!item?.title || !item?.notes || !item?.difficulty) continue;
        const diff = item.difficulty as "easy" | "medium" | "hard";
        if (!["easy", "medium", "hard"].includes(diff)) continue;

        await addTask({
          title: String(item.title),
          description: String(item.notes),
          difficulty: diff,
          due_date: item.due_date ?? null,
        });
        imported += 1;
      }

      Alert.alert("Import complete", `Added ${imported} tasks from clipboard.`);
    } catch (err) {
      console.error("Import failed", err);
      Alert.alert("Import failed", "Couldn't read tasks from clipboard.");
    }
  };

  const clearCompleted = async () => {
    Alert.alert(
      "Clear completed?",
      "This will remove all tasks marked as done.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Remove",
          style: "destructive",
          onPress: async () => {
            try {
              await deleteCompletedTasks();
              Alert.alert("Done", "Completed tasks were removed.");
            } catch (error) {
              console.error("Failed to clear completed tasks", error);
              Alert.alert("Couldn't clear tasks", "Please sign in again and retry.");
            }
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  const resetDemoData = async () => {
    Alert.alert(
      "Reset demo data?",
      "This will delete all tasks and add fresh dummy tasks.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Reset",
          style: "destructive",
          onPress: async () => {
            try {
              await deleteAllTasks();
              await seedDummyTasks();
              Alert.alert("Reset complete", "Dummy tasks have been reloaded.");
            } catch (error) {
              console.error("Failed to reset demo data", error);
              Alert.alert("Reset failed", "Please sign in again and retry.");
            }
          },
        },
      ],
      { userInterfaceStyle: dark ? "dark" : "light" }
    );
  };

  const handleToggleNotifications = useCallback(async () => {
    if (loadingReminders) return;
    setLoadingReminders(true);
    const nextValue = !notificationsEnabled;
    try {
      if (nextValue) {
        const ok = await enableReminder(reminderTime.hour, reminderTime.minute);
        if (!ok) {
          Alert.alert(
            "Notifications blocked",
            "Please enable notification permissions for this app to receive reminders."
          );
          setNotificationsEnabled(false);
          return;
        }
        setNotificationsEnabled(true);
      } else {
        await disableReminder();
        setNotificationsEnabled(false);
      }
    } catch (error) {
      console.error("Notification toggle failed", error);
      Alert.alert("Notifications error", "We couldn't update reminder settings. Please try again.");
    } finally {
      setLoadingReminders(false);
    }
  }, [loadingReminders, notificationsEnabled, reminderTime.hour, reminderTime.minute]);

  const handleTimeChange = useCallback((event: DateTimePickerEvent, date?: Date) => {
    if (event.type === "dismissed") return;
    if (!date) return;
    setTempTime({ hour: date.getHours(), minute: date.getMinutes() });
  }, []);

  const applyTempTime = useCallback(async () => {
    setShowTimePicker(false);
    setReminderTime(tempTime);
    setLoadingReminders(true);
    try {
      if (notificationsEnabled) {
        const ok = await enableReminder(tempTime.hour, tempTime.minute);
        if (!ok) {
          Alert.alert(
            "Notifications blocked",
            "Please enable notification permissions for this app to receive reminders."
          );
          setNotificationsEnabled(false);
        }
      } else {
        await saveReminderSettings({ enabled: false, hour: tempTime.hour, minute: tempTime.minute });
      }
    } catch (error) {
      console.error("Failed to update reminder time", error);
      Alert.alert("Notification error", "We couldn't update the reminder time.");
    } finally {
      setLoadingReminders(false);
    }
  }, [notificationsEnabled, tempTime]);

  const reminderTimeDisplay = useMemo(
    () => formatReminderTime(reminderTime.hour, reminderTime.minute),
    [reminderTime.hour, reminderTime.minute]
  );

  const refreshAccessPrefs = useCallback(async () => {
    setLoadingAccess(true);
    try {
      const prefs = await loadAccessibilityPrefs();
      setFontScaleState(prefs.fontScale);
      setHapticsEnabledState(prefs.hapticsEnabled);
      setColorBlindModeState(prefs.colorBlindMode);
    } finally {
      setLoadingAccess(false);
    }
  }, []);

  const handleSendTest = useCallback(async () => {
    if (!notificationsEnabled) {
      Alert.alert("Enable alerts first", "Turn on Enable Alerts to send a test notification.");
      return;
    }
    if (loadingReminders || sendingTest) return;
    setSendingTest(true);
    try {
      const ok = await triggerTestNotification();
      if (!ok) {
        Alert.alert(
          "Notifications blocked",
          "Please enable notification permissions for this app to receive alerts."
        );
      } else {
        Alert.alert("Sent", "A test notification is on its way.");
      }
    } catch (error) {
      console.error("Failed to send test notification", error);
      Alert.alert("Send failed", "Could not send a test notification. Please try again.");
    } finally {
      setSendingTest(false);
    }
  }, [notificationsEnabled, loadingReminders, sendingTest]);

  const handleFontScaleChange = useCallback(
    async (delta: number) => {
      const next = Math.min(1.6, Math.max(0.8, Number((fontScale + delta).toFixed(2))));
      setFontScaleState(next);
      await setFontScale(next);
    },
    [fontScale]
  );

  const handleToggleHaptics = useCallback(
    async (value: boolean) => {
      setHapticsEnabledState(value);
      await setHapticsEnabled(value);
    },
    []
  );

  const handleToggleColorBlind = useCallback(
    async (value: boolean) => {
      setColorBlindModeState(value);
      await setColorBlindMode(value);
    },
    []
  );

  return (
    <View style={{ flex: 1, backgroundColor: background }}>

      {/* 🔵 TOP BLUR EFFECT */}
      <BlurView
        intensity={40}
        tint={dark ? "dark" : "light"}
        pointerEvents="none"
        style={styles.blurHeader}
      />

      {/* Smooth fade under blur */}
      <View style={styles.blurFade} pointerEvents="none" />

      <ScrollView
        ref={scrollRef}
        style={styles.container}
        contentContainerStyle={{ paddingBottom: 70, paddingTop: 26 }}
      >

        {/* TITLE */}
        <Text style={[styles.title, { color: text }]}></Text>

        {/* ACCOUNT */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <TouchableOpacity
            style={styles.row}
            activeOpacity={0.9}
            onPress={() => router.push("/account")}
          >
            <Text style={[styles.label, { color: text }]}>Account</Text>
            <View style={{ flexDirection: "row", alignItems: "center" }}>
              <Text style={[styles.value, { color: subtext }]}>
                {user?.name || user?.email || "Guest"}
              </Text>
              <Ionicons name="chevron-forward" size={18} color={subtext} style={{ marginLeft: 6 }} />
            </View>
          </TouchableOpacity>
        </View>

        {/* TIME PICKER MODAL */}
        <Modal transparent visible={showTimePicker} animationType="fade" onRequestClose={() => setShowTimePicker(false)}>
          <TouchableOpacity
            activeOpacity={1}
            onPress={() => setShowTimePicker(false)}
            style={styles.modalOverlay}
          >
            <TouchableOpacity activeOpacity={1} style={[styles.pickerCard, { backgroundColor: card }]}>
              <Text style={[styles.modalTitle, { color: text }]}>Select Reminder Time</Text>
              <DateTimePicker
                mode="time"
                display={Platform.OS === "ios" ? "spinner" : "spinner"}
                value={new Date(new Date().setHours(tempTime.hour, tempTime.minute, 0, 0))}
                onChange={handleTimeChange}
                minuteInterval={5}
                themeVariant={dark ? "dark" : "light"}
              />
              <TouchableOpacity
                style={[styles.primaryButton, { backgroundColor: "#0A84FF" }]}
                onPress={applyTempTime}
                disabled={loadingReminders}
              >
                <Text style={styles.primaryButtonText}>Set</Text>
              </TouchableOpacity>
            </TouchableOpacity>
          </TouchableOpacity>
        </Modal>

        {/* SECURITY — surfaced above notifications to prioritize App Lock; headers removed for cleaner hierarchy */}
        <View style={[styles.card, { backgroundColor: card }]}>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>App Lock</Text>
            <Switch
              value={appLock}
              onValueChange={async (value) => {
                if (loadingLock) return;
                if (value) {
                  // Turning on: go to PIN setup; don't flip state until success.
                  router.push("/set-pin");
                } else {
                  // Turning off: require PIN confirmation.
                  router.push("/disable-app-lock");
                }
              }}
              disabled={loadingLock}
            />
          </View>

          {appLock && (
            <TouchableOpacity
              style={styles.row}
              activeOpacity={0.85}
              onPress={() => router.push("/change-pin")}
            >
              <Text style={[styles.label, { color: text }]}>Change PIN</Text>
              <Text style={[styles.value, { color: subtext }]}>Secure</Text>
            </TouchableOpacity>
          )}
        </View>

        {/* NOTIFICATIONS */}
        <View style={[styles.card, { backgroundColor: card }]}>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Enable Alerts</Text>
            <Switch
              value={notificationsEnabled}
              onValueChange={handleToggleNotifications}
              disabled={loadingReminders}
            />
          </View>

          <TouchableOpacity
            style={styles.row}
            onPress={() => {
              setTempTime(reminderTime);
              setShowTimePicker(true);
            }}
          >
            <Text style={[styles.label, { color: text }]}>Daily Reminder Time</Text>
            <Text style={[styles.value, { color: subtext }]}>{reminderTimeDisplay}</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.row}
            onPress={handleSendTest}
            disabled={loadingReminders || sendingTest}
          >
            <Text style={[styles.label, { color: text }]}>Send test notification</Text>
            <Text style={[styles.value, { color: subtext }]}>
              {sendingTest ? "Sending..." : "Now"}
            </Text>
          </TouchableOpacity>
        </View>

        {/* ACCESSIBILITY */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Text Size</Text>
            <View style={styles.sliderRow}>
              <TouchableOpacity
                style={[styles.pillBtn, { borderColor: subtext }]}
                onPress={() => handleFontScaleChange(-0.1)}
                disabled={loadingAccess}
              >
                <Text style={[styles.pillLabel, { color: text }]}>–</Text>
              </TouchableOpacity>
              <Text style={[styles.value, { color: subtext, width: 60, textAlign: "center" }]}>
                {Math.round(fontScale * 100)}%
              </Text>
              <TouchableOpacity
                style={[styles.pillBtn, { borderColor: subtext }]}
                onPress={() => handleFontScaleChange(0.1)}
                disabled={loadingAccess}
              >
                <Text style={[styles.pillLabel, { color: text }]}>+</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Haptics</Text>
            <Switch value={hapticsEnabled} onValueChange={handleToggleHaptics} disabled={loadingAccess} />
          </View>

          <View style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Color blind friendly</Text>
            <Switch
              value={colorBlindMode}
              onValueChange={handleToggleColorBlind}
              disabled={loadingAccess}
            />
          </View>
        </View>

        {/* NAVIGATION */}
        <View style={[styles.card, { backgroundColor: card }]}>

          <TouchableOpacity style={styles.row} onPress={() => router.push("/nav-quick-actions")}>
            <Text style={[styles.label, { color: text }]}>Nav Quick Actions</Text>
            <Text style={[styles.value, { color: subtext }]}>Customize</Text>
          </TouchableOpacity>
        </View>

        {/* DATA */}
        <View style={[styles.card, { backgroundColor: card }]}>

          <TouchableOpacity style={styles.row} onPress={exportTasks}>
            <Text style={[styles.label, { color: text }]}>Export tasks (clipboard JSON)</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={importTasks}>
            <Text style={[styles.label, { color: text }]}>Import tasks from clipboard</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={seedDummyTasks}>
            <Text style={[styles.label, { color: text }]}>Add 10 dummy tasks</Text>
            <Text style={[styles.value, { color: subtext }]}>Instant</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={clearCompleted}>
            <Text style={[styles.label, { color: text }]}>Clear completed tasks</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={resetDemoData}>
            <Text style={[styles.label, { color: text }]}>Reset demo data</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row} onPress={clearAllData}>
            <Text style={[styles.label, { color: "#FF3B30" }]}>
              Clear All Tasks
            </Text>
          </TouchableOpacity>
        </View>

        {/* ABOUT */}
        <View style={[styles.card, { backgroundColor: card }]}>
          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Version</Text>
            <Text style={[styles.value, { color: subtext }]}>1.0.0</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Developer</Text>
            <Text style={[styles.value, { color: subtext }]}>Tanveer Singh Dhaliwal</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Privacy Policy</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.row}>
            <Text style={[styles.label, { color: text }]}>Terms of Service</Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },

  title: {
    fontSize: 32,
    fontWeight: "700",
    marginHorizontal: 16,
    marginBottom: 20,
  },

  card: {
    borderRadius: 16,
    marginBottom: 24,
    paddingVertical: 8,
    marginHorizontal: 16,
    overflow: "hidden",
  },

  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 18,
  },

  label: { fontSize: 16 },
  value: { fontSize: 14, opacity: 0.8 },
  sliderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pillBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  pillLabel: { fontSize: 18, fontWeight: "700" },

  /* Blur header */
  blurHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 80,
    zIndex: 20,
  },

  /* Smooth fade under blur */
  blurFade: {
    position: "absolute",
    top: 80,
    left: 0,
    right: 0,
    height: 40,
    zIndex: 19,
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { height: 8, width: 0 },
    shadowRadius: 12,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  pickerCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  primaryButton: {
    marginTop: 12,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
});
